### PR TITLE
fix missing events from production builds

### LINKED ISSUE #98: production not showing upcoming events
The current production site is not showing the latest posted event
https://www.tuesdaystunes.tv
Image

The data is definitely coming back from the API, as I can see it on the main studio website too.
https://www.analogstudios.net/events/
Image

https://www.analogstudios.net/api/v2/events/?tag=tt
```json
[{"id":47,"title":"Tuesday's Tunes - 12/6/2022","description":"<p>Our next show is coming soon!  Check back for more details.</p>","startTime":1670374800,"endTime":1670378400,"tags":["tt"]},{"id":46,"title":"Tuesday's Tunes - 11/22/2022","description":"<p>Join us for our Tuesdays Tunes Thanksgiving Special!!</p>","startTime":1669165200,"endTime":1669168800,"link":"https://www.facebook.com/events/d41d8cd9/tuesdays-tunes-thanksgiving-special/935122507893117/","tags":["tt"]},{"id":45,"title":"Tuesday's Tunes - 11/08/2022","description":"<p>This Tuesday night is <a href=\"https://www.facebook.com/events/d41d8cd9/tuesdays-tunes-s3-e3/679540530554417/\">another episode</a>! Tune-in after election night to catch the show!</p>","startTime":1667955600,"endTime":1667959200,"link":"https://www.facebook.com/events/d41d8cd9/tuesdays-tunes-s3-e3/679540530554417/","tags":["tt"]}
```

This is working fine locally though.  🤷‍♂ 
Image

----

Have tried a couple builds to flush things but no luck.  Worst case will build locally and upload that 😠

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
resolve #98 

Things are working now in the preview environment 😮‍💨 
https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/issues/98#issuecomment-1336438896

## Summary of Changes
1. Update API endpoint in compliance with https://github.com/AnalogStudiosRI/www.analogstudios.net/issues/81 and removed the `/` (this was causing inconsistent results)
1. Refactored `getAttributes` logic as I don't think it was implemented correctly in the first place
1. Refactor even filtering since it looked to be a lot more complicated than it needed to be.

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
I _think- removing the `/` in _index.js_ was a key here as per https://github.com/AnalogStudiosRI/api/issues/16, and also the refactoring work in attributes parsing.  Either way, it is now working in the preview environment at least.

Maybe will play around with it a little more to narrow it down, but probably want to slam this through without much more delay since there is a show next week and we can't validate #99

File: src/pages/index.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ import '../components/youtube-playlist/youtube-playlist.js';
 
 export default class Home extends HTMLElement {
   async connectedCallback() {
-    const events = (await fetch('https://www.analogstudios.net/api/v2/events/?tag=tt')
+    const events = (await fetch('https://www.analogstudios.net/api/v2/events?tag=tt')
```
Comment (thescientist13) [inline src/pages/index.js:9]: Seems related to changes made as part of https://github.com/AnalogStudiosRI/www.analogstudios.net/issues/81
